<?php

namespace FootBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FootballPlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FootballPlayerRepository extends EntityRepository
{
}
